# Generated by Django 4.2.2 on 2023-07-14 08:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_create_date_alter_blog_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='create_date',
            field=models.DateField(blank=True, default=datetime.date(2023, 7, 14), null=True, verbose_name='дата создания'),
        ),
    ]
